services:
  db:
    image: mysql:8.0
    container_name: smartpark-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  auth:
    build: ../smartpark-auth
    image: smartpark-auth
    container_name: smartpark-auth
    ports:
      - "9000:8000"
    volumes:
      - ../smartpark-auth:/var/www
    command: bash -c "
        composer install &&
        php artisan key:generate --force &&
        php artisan jwt:secret --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    depends_on:
      - db
    env_file:
      - ../smartpark-auth/.env

  backend:
    build: ../smartpark-backend
    image: smartpark-backend
    container_name: smartpark-backend
    ports:
      - "8000:8000"
    volumes:
      - ../smartpark-backend:/var/www
      - ../smartpark-auth:/var/www/../smartpark-auth 
    command: bash -c "
        composer install &&
        php artisan key:generate --force &&
        php artisan jwt:secret --force &&
        php artisan migrate --force &&
        php artisan swagger:merge &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    depends_on:
      - db
      - auth
    env_file:
      - ../smartpark-backend/.env

volumes:
  db_data:
